theme: jekyll-theme-midnight
title: "Student Service Site"
description: "Studying and planning resources from students, to students."
gitorg: "https://github.com/jm1021/leuck_reunion"
description: "June 26 to July 1 2023"
google_analytics: G-PFHSSXMJCJ

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one